# Generated by Django 3.2 on 2021-06-19 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_project_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='tag',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
